services:
  - type: web
    name: salesiq-ai-backend
    runtime: python
    rootDir: backend
    region: oregon

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server_fixed:app --host 0.0.0.0 --port 10000

    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
